name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 16.20.1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
      - name: pull nuxt
        run: |
          pnpm dlx nuxi@latest init nuxt-project
          cd nuxt-project
          pnpm install
