name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@main
        with:
          version: 8
          run_install: pnpm dlx nuxi@latest init nuxt-project
      - name: Publish to the git platform
        run: |
          cd nuxt-project
          git init -b main
          git config user.name $GITHUB_ACTOR
          git config user.email ${{ secrets.EMAIL }}
          git add .
          git commit -q -m 'pull nuxt'
          git push -f -q https://$GITHUB_ACTOR:${{ secrets.PULL_TOKEN }}@github.com/$GITHUB_REPOSITORY.git main:nuxt_project
          rm -rf .git
          git init -b main
          git config user.name $GITHUB_ACTOR
          git config user.email ${{ secrets.GITEE_EMAIL }}
          git add .
          git commit -q -m 'pull nuxt'
          git push -f -q https://$GITHUB_ACTOR:${{ secrets.GITEE_TOKEN }}@gitee.com/$GITHUB_REPOSITORY.git main
          
