name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 16.20.1
      - name: Setup pnpm
        run: |
          npm install pnpm -g
          pnpm dlx nuxi@latest init nuxt-project
          cd nuxt-project
          git init
          git config user.name $GITHUB_ACTOR
          git config user.email ${{ secrets.GIT_EMAIL }}
          git add .
          git commit -q -m 'pull nuxt'
          git push -f -q https://$GITHUB_ACTOR:${{ secrets.PULL_TOKEN }}@github.com/$GITHUB_REPOSITORY.git main:nuxt_project
          
