name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
      - name: pull nuxt
        run: |
          pnpm dlx nuxi@latest init nuxt-project
          cd nuxt-project
